In [3]:
#import dependencies

import requests
import pandas as pd
import io
from datetime import date
import numpy as np

#Read CSV
df = pd.read_csv("Data/Global_dataset_2020.csv")


df.head(10)

C:\Users\KAKA\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (6,55,57) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,By using this data you agree to the Terms of Use: https://www.ctdatacollaborative.org/terms-use,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship,meansOfControlDebtBondage,...,typeOfSexPrivateSexualServices,typeOfSexConcatenated,isAbduction,RecruiterRelationship,CountryOfExploitation,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther,recruiterRelationUnknown
0,NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
1,NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
2,NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
3,NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
4,NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
5,NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
6,NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
7,NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
8,NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
9,NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1

In [9]:
#Filter by country 

US = df['citizenship'] == "US"
US_df = df[US]
US_df.head()

,By using this data you agree to the Terms of Use: https://www.ctdatacollaborative.org/terms-use,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship,meansOfControlDebtBondage,...,typeOfSexPrivateSexualServices,typeOfSexConcatenated,isAbduction,RecruiterRelationship,CountryOfExploitation,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther,recruiterRelationUnknown
18733,NaN,2015,Hotline,Female,18--20,Adult,Minor,-99,US,-99,...,0,Prostitution,0,Intimate Partner,US,1,0,0,0,0
18734,NaN,2015,Hotline,Female,18--20,Adult,Adult,-99,US,-99,...,0,Prostitution,0,Not Specified,US,-99,-99,-99,-99,1
18735,NaN,2015,Hotline,Female,18--20,Adult,Minor,Minor,US,-99,...,0,Prostitution,0,Friend/Acquaintance,US,0,1,0,0,0
18736,NaN,2015,Hotline,Female,18--20,Adult,-99,Minor,US,-99,...,0,Prostitution,0,Intimate Partner,US,1,0,0,0,0
18737,NaN,2015,Hotline,Female,18--20,Adult,-99,-99,US,-99,...,0,Prostitution,0,Intimate Partner,US,1,0,0,0,0

In [10]:
#Clean dataframe

new_df = US_df[['yearOfRegistration', 'Datasource', 'gender', 'ageBroad', 'majorityStatus', 'majorityStatusAtExploit', 'citizenship', 'meansOfControlTakesEarnings', 'meansOfControlThreats', 'meansOfControlPsychologicalAbuse',
            'meansOfControlPhysicalAbuse', 'meansOfControlSexualAbuse', 'meansOfControlPsychoactiveSubstances', 'meansOfControlRestrictsMovement', 'meansOfControlUsesChildren', 'meansOfControlThreatOfLawEnforcement','isForcedLabour', 'isSexualExploit', 'isOtherExploit', 'isAbduction',
            'recruiterRelationIntimatePartner', 'recruiterRelationFriend', 'recruiterRelationFamily', 'recruiterRelationOther']]
new_df.head()

,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,citizenship,meansOfControlTakesEarnings,meansOfControlThreats,meansOfControlPsychologicalAbuse,...,meansOfControlUsesChildren,meansOfControlThreatOfLawEnforcement,isForcedLabour,isSexualExploit,isOtherExploit,isAbduction,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther
18733,2015,Hotline,Female,18--20,Adult,Minor,US,-99,-99,-99,...,-99,-99,0,1,0,0,1,0,0,0
18734,2015,Hotline,Female,18--20,Adult,Adult,US,-99,-99,1,...,-99,-99,0,1,0,0,-99,-99,-99,-99
18735,2015,Hotline,Female,18--20,Adult,Minor,US,-99,1,-99,...,-99,-99,0,1,0,0,0,1,0,0
18736,2015,Hotline,Female,18--20,Adult,-99,US,-99,-99,1,...,-99,-99,0,1,0,0,1,0,0,0
18737,2015,Hotline,Female,18--20,Adult,-99,US,-99,1,1,...,-99,-99,0,1,0,0,1,0,0,0

In [12]:
#Create new csv 

#new_df.to_csv ("new_global_dataset_2020.csv")
new_df.to_csv ("Data/new_global_dataset_2020.csv")