In [1]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None 

# File to Load (Remember to Change These)
ds = "Data/new_global_dataset_2020.csv"

# Read Purchasing File and store into Pandas data frame
ds_df = pd.read_csv(ds)

ds_df.head()

,Unnamed: 0,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,citizenship,meansOfControlTakesEarnings,meansOfControlThreats,...,meansOfControlUsesChildren,meansOfControlThreatOfLawEnforcement,isForcedLabour,isSexualExploit,isOtherExploit,isAbduction,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther
0,18733,2015,Hotline,Female,18--20,Adult,Minor,US,-99,-99,...,-99,-99,0,1,0,0,1,0,0,0
1,18734,2015,Hotline,Female,18--20,Adult,Adult,US,-99,-99,...,-99,-99,0,1,0,0,-99,-99,-99,-99
2,18735,2015,Hotline,Female,18--20,Adult,Minor,US,-99,1,...,-99,-99,0,1,0,0,0,1,0,0
3,18736,2015,Hotline,Female,18--20,Adult,-99,US,-99,-99,...,-99,-99,0,1,0,0,1,0,0,0
4,18737,2015,Hotline,Female,18--20,Adult,-99,US,-99,1,...,-99,-99,0,1,0,0,1,0,0,0